Repository Peripli/service-manager, pull requests merged in 2018-07, with the labels that each got.

#60 Authenticator
  Gopkg.lock
  Gopkg.toml
  application.yml
  authentication/authenticationfakes/fake_authenticator.go
  authentication/authenticationfakes/fake_token.go
  authentication/authenticationfakes/fake_token_verifier.go
  authentication/interfaces.go
  authentication/oidc/oidc.go
  authentication/oidc/oidc_test.go
  authentication/oidc/types.go
  authentication/types.go
Labels: request review

#80 Use vendor-only on dep install
  .travis.yml
Labels: request review

#76 Filters & Plugins
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  README.md
  api/api.go
  api/api_test.go
  api/broker/broker.go
  api/broker/broker_controller.go
  api/catalog/catalog.go
  api/catalog/catalog_controller.go
  api/common/common.go
  api/common/common_test.go
  api/info/info.go
  api/info/info_controller.go
  api/osb/controller.go
  api/osb/controller_test.go
  api/osb/logic.go
  api/osb/logic_test.go
  api/platform/platform.go
  api/platform/platform_controller.go
  app/sm.go
  app/sm_test.go
  docs/plugins.md
  main.go
  pkg/plugin/plugin.go
  pkg/web/errors.go
  pkg/web/types.go
  rest/api.go
  rest/api_test.go
  rest/errors.go
  rest/errors_test.go
  rest/filters.go
  rest/filters_test.go
  rest/handler.go
  rest/handler_test.go
  rest/interfaces.go
  rest/util.go
  server/server.go
  test/broker_test/broker_test.go
  test/catalog_test/catalog_test.go
  test/common/common.go
  test/common/test_context.go
  test/filter_test/filter_test.go
  test/info_test/info_test.go
  test/osb_test/osb_test.go
  test/platform_test/platform_test.go
  test/plugin_test/plugin_test.go
Labels: review in progress

#86 Input validation
  Gopkg.lock
  rest/interfaces.go
  rest/util.go
  test/platform_test/platform_test.go
  types/platform.go
  validator/validator.go
  validator/validator_test.go
Labels: request review, review in progress

#89 Add copyright on main.go
  main.go
Labels: bug, request review, review in progress

#90 Add unit tests for postgres storage
  storage/postgres/abstract_test.go
  storage/postgres/postgres_suite_test.go
  storage/postgres/storage_test.go
Labels: request review

#91 Add healthcheck API
  api/api.go
  api/healthcheck/healthcheck.go
  api/healthcheck/healthcheck_controller.go
  api/healthcheck/healthcheck_controller_test.go
  storage/interfaces.go
  storage/postgres/storage.go
  storage/postgres/storage_state.go
  storage/postgres/storage_state_test.go
  storage/postgres/storage_test.go
  storage/storagefakes/fake_broker.go
  storage/storagefakes/fake_storage.go
  test/healthcheck_test/healthcheck_test.go
Labels: request review

#93 Refactor authencation
  app/app.go
  application.yml
  authentication/types.go
  config/config.go
  config/config_test.go
  filters/auth/auth.go
  filters/auth/filters.go
  pkg/servicemanager/sm_test.go
  test/common/application.yml
  test/healthcheck_test/healthcheck_test.go
  test/info_test/info_test.go
Labels: review in progress

#94 Remove credentials table
  api/broker/broker_controller.go
  api/catalog/catalog_controller.go
  api/platform/platform_controller.go
  authentication/basic/basic.go
  storage/interfaces.go
  storage/postgres/abstract.go
  storage/postgres/abstract_test.go
  storage/postgres/broker.go
  storage/postgres/credentials.go
  storage/postgres/migrations/001_initial_schema.down.sql
  storage/postgres/migrations/001_initial_schema.up.sql
  storage/postgres/migrations/002_add_catalog_to_brokers.down.sql
  storage/postgres/migrations/002_add_catalog_to_brokers.up.sql
  storage/postgres/platform.go
  storage/postgres/storage.go
  storage/postgres/storage_test.go
  storage/postgres/types.go
  storage/storagefakes/fake_platform.go
Labels: To be merged
