Repository Peripli/service-manager, pull requests merged in 2018-08, with the labels that each got.

#100 Fix k8s deployment
  Dockerfile
  deployment/k8s/charts/service-manager/requirements.lock
  deployment/k8s/charts/service-manager/templates/sm02-configmap.yaml
  deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
  deployment/k8s/charts/service-manager/values.yaml
  docs/plugins.md
Labels: request review

#103 Create .dockerignore
  .dockerignore
Labels: To be merged, request review

#96 Securely store credentials
  Gopkg.lock
  Gopkg.toml
  api/api.go
  api/api_test.go
  api/broker/broker_controller.go
  api/filters/authn/basic.go
  api/osb/osb_controller.go
  api/platform/platform_controller.go
  application.yml
  config/config.go
  config/config_test.go
  deployment/cf/manifest.yml
  deployment/k8s/charts/service-manager/templates/sm01-secret.yaml
  deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
  pkg/log/log.go
  pkg/sm/sm.go
  pkg/types/credentials.go
  security/basic/authenticator.go
  security/basic/authenticator_test.go
  security/encrypt.go
  security/encrypter.go
  security/interfaces.go
  security/securityfakes/fake_encrypter.go
  security/securityfakes/fake_key_fetcher.go
  security/securityfakes/fake_key_setter.go
  server/server.go
  storage/interfaces.go
  storage/postgres/migrations/002_encryption.down.sql
  storage/postgres/migrations/002_encryption.up.sql
  storage/postgres/security.go
  storage/postgres/security_test.go
  storage/postgres/storage.go
  storage/postgres/storage_test.go
  storage/postgres/types.go
  storage/registry.go
  storage/registry_test.go
  storage/storagefakes/fake_storage.go
  test/common/application.yml
  test/security_test/two_layer_encrypter_test.go
  test/sm/sm_test.go
Labels: request review

#102 Proxy last operation call
  .gometalinter.json
  api/osb/osb.go
  pkg/web/api.go
  pkg/web/plugin.go
  test/common/common.go
  test/common/test_context.go
  test/osb_test/osb_test.go
  test/plugin_test/plugin_test.go
Labels: request review

#105 Fix: wrong path when broker has a url path suffix
  api/osb/osb_controller.go
  test/common/common.go
  test/osb_test/osb_test.go
Labels: To be merged, request review

#104 Configure server host
  server/server.go
Labels: To be merged

#109 Fix race conditions in tests
  storage/registry_test.go
Labels: request review

#111 enhance filter logging
  pkg/web/filter.go
Labels: request review

#117 Fix k8s deployment template indentation
  deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
Labels: request review

#115 Allow for custom validation of token claims
  api/api.go
  api/broker/broker.go
  api/catalog/catalog.go
  api/filters/authn/authn.go
  api/filters/authn/authn_test.go
  api/filters/authn/basic.go
  api/filters/authn/bearer.go
  api/filters/authn/required.go
  api/healthcheck/healthcheck.go
  api/info/info.go
  api/osb/osb.go
  api/osb/osb_controller.go
  api/platform/platform.go
  config/config_test.go
  pkg/web/context_keys.go
  pkg/web/routes.go
  pkg/web/user.go
  pkg/web/webfakes/fake_token_data.go
  security/basic/authenticator.go
  security/interfaces.go
  security/oidc/authenticator.go
  security/oidc/authenticator_test.go
  security/oidc/verifier.go
  security/securityfakes/fake_authenticator.go
  security/securityfakes/fake_token_verifier.go
  storage/interfaces.go
  storage/storagefakes/fake_platform.go
Labels: request review

#124 Switch from satori/go.uuid
  Gopkg.lock
  Gopkg.toml
  api/broker/broker_controller.go
  api/platform/platform_controller.go
Labels: bug, request review

#108 Filter ordering
  api/filters/authn/basic.go
  api/filters/authn/bearer.go
  pkg/util/slice/strings.go
  pkg/web/api.go
  pkg/web/api_test.go
  test/auth_test/auth_test.go
  test/broker_test/broker_test.go
  test/catalog_test/catalog_test.go
  test/common/test_context.go
  test/filter_test/filter_test.go
  test/healthcheck_test/healthcheck_test.go
  test/info_test/info_test.go
  test/osb_test/osb_test.go
  test/platform_test/platform_test.go
  test/plugin_test/plugin_test.go
Labels: request review

#125 Log URL when making call to external service
  pkg/util/client.go
Labels: request review

#128 Refactor component tests
  api/api_test.go
  api/broker/broker_controller.go
  test/auth_test/auth_test.go
  test/broker_test/broker_test.go
  test/catalog_test/catalog_test.go
  test/common/common.go
  test/common/oauth_server.go
  test/common/test_context.go
  test/filter_test/filter_test.go
  test/healthcheck_test/healthcheck_test.go
  test/info_test/info_test.go
  test/osb_test/osb_test.go
  test/platform_test/platform_test.go
  test/plugin_test/plugin_test.go
  test/sm/sm_test.go
Labels: request review, review in progress
