Repository Peripli/service-manager, pull requests merged in 2018-10, with the labels that each got.

#143 Release connection on ping
  storage/postgres/storage_state.go
Labels: bug, priority/high, request review

#135 Reusable log interceptor
  pkg/util/errors_test.go
  pkg/web/matcher_test.go
  security/oidc/authenticator_test.go
  test/testutil/log_interceptor.go
Labels: request review

#146 Add makefile
  .travis.yml
  Makefile
Labels: request review

#147 SM Docs
  CONTRIBUTING.md
  README.md
  application.yml
  deployment/cf/README.md
  deployment/cf/manifest.yml
  deployment/k8s/README.md
  deployment/k8s/charts/service-manager/values.yaml
  docs/README.md
  docs/concepts/components.md
  docs/concepts/glossary.md
  docs/concepts/introduction.md
  docs/development/README.md
  docs/development/build.md
  docs/development/code-standards.md
  docs/development/contrib-process.md
  docs/development/dep.md
  docs/development/extensions.md
  docs/development/prerequisites.md
  docs/development/repositories-structure.md
  docs/development/tests.md
  docs/diagrams/SM-overview.png
  docs/diagrams/Services-Platforms.png
  docs/diagrams/Services-SM-Platforms.png
  docs/install/README.md
  docs/install/cf-proxy.md
  docs/install/cli.md
  docs/install/k8s-proxy.md
  docs/install/sm.md
  docs/logos/big-sm-logo-with-text-black.png
  docs/logos/small-sm-logo-with-text-black.png
  docs/logos/small-sm-logo-with-text-green.png
  docs/usage/example-usage.md
  docs/usage/walkthrough.md
Labels: request review

#158 Fix setting correlation id header
  api/filters/logging_test.go
  pkg/log/request.go
Labels: request review

#134 Remove aggregated catalog
  PULL_REQUEST_TEMPLATE.md
  api/api.go
  api/catalog/catalog.go
  api/catalog/catalog_controller.go
  api/filters/authn/bearer.go
  api/filters/authn/required.go
  docs/development/extensions.md
  pkg/web/routes.go
  storage/postgres/storage.go
  storage/postgres/storage_test.go
  test/auth_test/auth_test.go
  test/catalog_test/catalog_test.go
Labels: request review

#140 Make authentication decision more generic
  api/api.go
  api/broker/broker_controller.go
  api/filters/authn/authn.go
  api/filters/authn/authn_test.go
  api/filters/authn/basic.go
  api/filters/authn/basic/basic.go
  api/filters/authn/basic/basic_test.go
  api/filters/authn/bearer.go
  api/filters/authn/oauth/authenticator.go
  api/filters/authn/oauth/authenticator_test.go
  api/filters/authn/oauth/filter.go
  api/filters/authn/oauth/verifier.go
  api/filters/authn/required.go
  api/osb/broker_fetcher.go
  api/platform/platform_controller.go
  docs/development/repositories-structure.md
  pkg/security/encrypt.go
  pkg/security/encrypter.go
  pkg/security/errors.go
  pkg/security/filters/required_authn.go
  pkg/security/filters/required_authz.go
  pkg/security/filters/required_test.go
  pkg/security/interfaces.go
  pkg/security/middlewares/authn.go
  pkg/security/middlewares/authz.go
  pkg/security/middlewares/common.go
  pkg/security/middlewares/middlewares_test.go
  pkg/security/securityfakes/fake_authenticator.go
  pkg/security/securityfakes/fake_authorizer.go
  pkg/security/securityfakes/fake_encrypter.go
  pkg/security/securityfakes/fake_key_fetcher.go
  pkg/security/securityfakes/fake_key_setter.go
  pkg/security/securityfakes/fake_token_verifier.go
  pkg/sm/sm.go
  pkg/util/errors.go
  pkg/web/context_keys.go
  storage/interfaces.go
  storage/postgres/security.go
  storage/postgres/security_test.go
  test/security_test/two_layer_encrypter_test.go
Labels: To be merged, request review

#163 Add links to cf summit sessions
  README.md
Labels: request review

#168 Local Install Documentaion
  application.yml
  deployment/cf/manifest.yml
  docs/README.md
  docs/development/README.md
  docs/development/build.md
  docs/development/dep.md
  docs/development/develop-prerequisites.md
  docs/development/extensions.md
  docs/development/install-prerequisites.md
  docs/development/local.md
  docs/development/prerequisites.md
  docs/development/tests.md
  docs/install/README.md
  docs/install/cf-proxy.md
  docs/install/k8s-proxy.md
  docs/install/sm.md
Labels: request review
