Repository Peripli/service-manager, pull requests merged in 2019-06, with the labels that each got.

#292 Construct SMBuilder with config instead of environment
  config/config.go
  config/config_test.go
  main.go
  pkg/env/cf.go
  pkg/env/cf_test.go
  pkg/env/env.go
  pkg/log/context.go
  pkg/sm/sm.go
  storage/interfaces.go
  storage/postgres/storage.go
  storage/postgres/storage_test.go
  storage/registry.go
  test/common/test_context.go
  test/sm_test/sm_test.go
Labels: request review

#280 Expose notification creation
  storage/interceptors/notifications_interceptor.go
  test/common/test_context.go
  test/ws_notification_test/ws_notification_test.go
Labels: request review

#296 Allow pflag creation for slices
  Gopkg.lock
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/helpers.go
Labels: release, request review

#289 [Fixit] Do not send last_notification_revision when no notifications are available
  api/notifications/notifications.go
  storage/postgres/notification_storage.go
  storage/postgres/notificator_test.go
  test/ws_notification_test/ws_notification_test.go
Labels: breaking change, request review

#295 [Fixit] Introduce SQL query builder
  Gopkg.lock
  pkg/query/selection.go
  storage/postgres/abstract.go
  storage/postgres/abstract_test.go
  storage/postgres/keystore.go
  storage/postgres/labels.go
  storage/postgres/labels_test.go
  storage/postgres/notification_storage.go
  storage/postgres/query_builder.go
  storage/postgres/query_builder_test.go
  storage/postgres/storage.go
  test/platform_test/platform_test.go
  test/ws_notification_test/ws_notification_test.go
Labels: request review

#297 Extend supported content types for APIs
  pkg/util/api.go
  pkg/util/api_test.go
Labels: request review

#288 Update k8s deployment
  deployment/k8s/charts/service-manager/Chart.yaml
  deployment/k8s/charts/service-manager/requirements.lock
  deployment/k8s/charts/service-manager/requirements.yaml
  deployment/k8s/charts/service-manager/templates/_helpers.tpl
  deployment/k8s/charts/service-manager/templates/sm01-secret.yaml
  deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml
  deployment/k8s/charts/service-manager/values.yaml
  docs/install/sm.md
Labels: request review

#300 Do not return empty labels when no labels are present in database
  storage/postgres/interfaces.go
  test/storage_test/storage_test.go
Labels: bug, request review

#303 Delete by Label Query/Criteria
  storage/postgres/abstract.go
  storage/postgres/query_builder.go
  storage/postgres/query_builder_test.go
  test/delete_list.go
  test/list.go
Labels: request review

#304 Simplify User Context
  api/api.go
  api/filters/basic_authentication.go
  api/filters/basic_authentication_test.go
  api/filters/filters_suite_test.go
  api/filters/protected_labels.go
  api/filters/protected_labels_test.go
  api/filters/visibility_for_platform.go
  api/notifications/notifications.go
  pkg/security/authenticators/oidc_authenticator.go
  pkg/security/authenticators/oidc_authenticator_test.go
  pkg/web/user.go
  pkg/web/webfakes/fake_data.go
Labels: request review

#306 Fix deletion query building
  storage/postgres/query_builder.go
  storage/postgres/query_builder_test.go
Labels: bug, request review

#308 Add context to serve error logging
  api/filters/recovery.go
  api/http_handler.go
  api/notifications/ws_connection.go
  api/osb/osb_controller.go
  pkg/util/errors.go
  pkg/util/errors_test.go
Labels: request review

#307 Make test SM server listener replaceable
  test/common/test_context.go
Labels: request review

#305 Multitenant Resource Access
  .gitignore
  api/api.go
  api/api_test.go
  api/base_controller.go
  api/filters/protected_labels.go
  api/filters/protected_labels_test.go
  api/filters/tenant_filter.go
  api/filters/tenant_filter_test.go
  config/config.go
  main.go
  pkg/multitenancy/token_extraction.go
  pkg/multitenancy/token_extraction_test.go
  pkg/sm/sm.go
  storage/encrypting_repository.go
  storage/encrypting_repository_test.go
  storage/interceptable_repository.go
  storage/interceptable_repository_test.go
  storage/interceptors/broker_update_catalog_interceptor.go
  storage/interceptors/visibility_notifications_interceptor.go
  storage/interfaces.go
  storage/postgres/notification_storage.go
  storage/postgres/storage.go
  storage/storagefakes/fake_storage.go
  test/broker_test/broker_test.go
  test/common/application.yml
  test/common/test_context.go
  test/delete.go
  test/delete_list.go
  test/get.go
  test/interceptors_test/interceptors_test.go
  test/list.go
  test/notification_cleaner_test/notification_cleaner_test.go
  test/notification_test/notification_test.go
  test/patch.go
  test/platform_test/platform_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/storage_test/storage_test.go
  test/test.go
  test/visibility_test/visibility_test.go
  test/ws_notification_test/ws_notification_test.go
Labels: request review
