Repository Peripli/service-manager, pull requests merged in 2019-11, with the labels that each got.

#346 Fix panic: index out of range
  pkg/query/selection.go
  pkg/query/selection_test.go
  storage/postgres/query_builder_test.go
  storage/postgres/where_clause_tree.go
Labels: request review

#331 Add config api endpoint
  Gopkg.lock
  api/api.go
  api/api_test.go
  api/configuration/controller.go
  api/filters/oidc_authentication.go
  config/config.go
  config/config_test.go
  main.go
  pkg/env/env.go
  pkg/env/envfakes/fake_environment.go
  pkg/security/filters/required_authn.go
  pkg/sm/sm.go
  test/auth_test/auth_test.go
  test/common/test_context.go
  test/configuration_test/configuration_test.go
  test/logging_test/logging_test.go
  test/sm_test/sm_test.go
Labels: request review

#348 Increase go version to 1.12
  .travis.yml
  Dockerfile
Labels: wip

#350 Change go version to 1.12.7
  Dockerfile
Labels: request review

#352 Introduce Operation resource
  Gopkg.lock
  pkg/types/notification.go
  pkg/types/operation.go
  pkg/types/operation_gen.go
  storage/interceptors/notifications_interceptor.go
  storage/postgres/keystore_test.go
  storage/postgres/migrations/20191117212400_operations.down.sql
  storage/postgres/migrations/20191117212400_operations.up.sql
  storage/postgres/notification.go
  storage/postgres/operation.go
  storage/postgres/operation_gen.go
  storage/postgres/storage.go
Labels: 👋request review

#353 Introduce Service Instance resource
  Gopkg.lock
  api/api.go
  api/service_instance_controller.go
  pkg/types/service_instance.go
  pkg/types/serviceinstance_gen.go
  pkg/web/routes.go
  storage/postgres/keystore_test.go
  storage/postgres/migrations/20191118203400_service_instances.down.sql
  storage/postgres/migrations/20191118203400_service_instances.up.sql
  storage/postgres/service_instance.go
  storage/postgres/serviceinstance_gen.go
  storage/postgres/storage.go
  test/broker_test/broker_test.go
  test/common/test_context.go
  test/list.go
  test/platform_test/platform_test.go
  test/service_instance_test/service_instance_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/test.go
  test/visibility_test/visibility_test.go
Labels: 👋request review

#356 Introduce Service Instance labelling interceptor
  api/api.go
  pkg/sm/sm.go
  storage/interceptors/service_instance_create_interceptor.go
  test/service_instance_test/service_instance_test.go
Labels: 👋request review

#359 Add authentication for service instance endpoint
  api/filters/basic_authentication.go
  api/filters/oidc_authentication.go
  api/filters/tenant_filter.go
  api/filters/tenant_filter_test.go
  pkg/security/filters/required_authn.go
  test/auth_test/auth_test.go
  test/service_instance_test/service_instance_test.go
Labels: 👋request review

#362 Regenerate the ANTLR parser
  pkg/query/parser/query_base_listener.go
  pkg/query/parser/query_lexer.go
  pkg/query/parser/query_listener.go
  pkg/query/parser/query_parser.go
Labels: 👋request review
