Repository Peripli/service-manager, pull requests merged in 2019-02, with the labels that each got.

#225 Redesign test context creation
  api/api_test.go
  test/auth_test/auth_test.go
  test/broker_test/broker_test.go
  test/common/broker.go
  test/common/catalog.go
  test/common/common.go
  test/common/oauth_server.go
  test/common/test_context.go
  test/filter_test/filter_test.go
  test/filter_test/public_plans_test.go
  test/healthcheck_test/healthcheck_test.go
  test/info_test/info_test.go
  test/osb_test/osb_test.go
  test/plugin_test/plugin_test.go
  test/sm_test/sm_test.go
  test/test.go
Labels: request review

#223 Broker API response now returns "service_brokers" instead of "brokers"
  pkg/types/broker.go
  test/broker_test/broker_test.go
  test/common/common.go
  test/delete_list.go
  test/list.go
Labels: breaking change, request review

#227 Test Broker request body not usable
  test/common/broker.go
Labels: bug, priority/high, request review

#228 Patch service broker with duplicate plans per service
  api/broker/broker_controller.go
  test/broker_test/broker_test.go
Labels: bug, priority/high

#232 Omit platform credentials for Platform PATCH API response
  api/platform/platform_controller.go
  test/platform_test/platform_test.go
Labels: request review
