Repository Peripli/service-manager, pull requests merged in 2019-10, with the labels that each got.

#333 Support token parameter for paging
  api/api.go
  api/base_controller.go
  api/filters/paging.go
  api/filters/paging_test.go
  api/service_offering_controller.go
  api/service_plan_controller.go
  docs/development/paging.md
  pkg/query/selection_test.go
  pkg/types/base.go
  pkg/types/interfaces.go
  pkg/web/web_suite_test.go
  storage/postgres/abstract.go
  storage/postgres/broker.go
  storage/postgres/keystore.go
  storage/postgres/keystore_test.go
  storage/postgres/migrations/20190913161000_paging.down.sql
  storage/postgres/migrations/20190913161000_paging.up.sql
  storage/postgres/platform.go
  storage/postgres/query_builder.go
  storage/postgres/query_builder_test.go
  storage/postgres/scheme_test.go
  storage/postgres/service_offering.go
  storage/postgres/service_plan.go
  storage/postgres/storage.go
  storage/postgres/subquery.go
  storage/postgres/visibility.go
  storage/postgres/where_clause_tree.go
  test/auth_test/auth_test.go
  test/broker_test/broker_test.go
  test/common/common.go
  test/common/test_context.go
  test/delete.go
  test/delete_list.go
  test/filter_test/filter_test.go
  test/get.go
  test/interceptors_test/interceptors_test.go
  test/list.go
  test/notification_test/notification_test.go
  test/patch.go
  test/platform_test/platform_test.go
  test/public_plans_interceptor_test/public_plans_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/sm_test/sm_test.go
  test/test.go
  test/visibility_test/visibility_test.go
Labels: request review

#317 Filter resources based on visibilities (only for platform)
  api/api.go
  api/filters/helpers.go
  api/filters/plans_filter_by_visibility.go
  api/filters/services_filter_by_visibility.go
  api/filters/visibility_filtering_middleware.go
  api/plugins/catalog_filter_by_visibility_plugin.go
  pkg/query/selection.go
  pkg/query/selection_test.go
  pkg/sm/sm.go
  pkg/types/platform.go
  test/broker_test/broker_test.go
  test/common/common.go
  test/delete_list.go
  test/list.go
  test/osb_test/osb_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
Labels: ok to merge, request review

#330 Paging for List operations
  api/api.go
  api/base_controller.go
  api/filters/plans_filter_by_visibility.go
  api/filters/services_filter_by_visibility.go
  api/filters/visibility_filtering_middleware.go
  api/service_offering_controller.go
  api/service_plan_controller.go
  docs/development/paging.md
  pkg/query/selection.go
  pkg/query/selection_test.go
  pkg/types/base.go
  pkg/types/interfaces.go
  pkg/util/api_test.go
  pkg/util/client.go
  pkg/util/list.go
  pkg/util/list_test.go
  pkg/util/util_suite_test.go
  pkg/web/web_suite_test.go
  storage/encrypting_repository.go
  storage/interceptable_repository.go
  storage/interfaces.go
  storage/postgres/abstract.go
  storage/postgres/broker.go
  storage/postgres/keystore.go
  storage/postgres/keystore_test.go
  storage/postgres/migrations/20190913161000_paging.down.sql
  storage/postgres/migrations/20190913161000_paging.up.sql
  storage/postgres/platform.go
  storage/postgres/query_builder.go
  storage/postgres/query_builder_test.go
  storage/postgres/scheme_test.go
  storage/postgres/service_offering.go
  storage/postgres/service_plan.go
  storage/postgres/storage.go
  storage/postgres/subquery.go
  storage/postgres/visibility.go
  storage/postgres/where_clause_tree.go
  storage/storagefakes/fake_storage.go
  test/auth_test/auth_test.go
  test/broker_test/broker_test.go
  test/common/common.go
  test/common/test_context.go
  test/delete.go
  test/delete_list.go
  test/filter_test/filter_test.go
  test/get.go
  test/interceptors_test/interceptors_test.go
  test/list.go
  test/notification_test/notification_test.go
  test/osb_test/osb_test.go
  test/patch.go
  test/platform_test/platform_test.go
  test/public_plans_interceptor_test/public_plans_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/sm_test/sm_test.go
  test/test.go
  test/visibility_test/visibility_test.go
Labels: request review

#339 Manage platform status during ping/pong flow
  Gopkg.lock
  api/api.go
  api/notifications/notification_controller.go
  api/notifications/notifications.go
  api/notifications/ws_connection.go
  pkg/sm/sm.go
  pkg/ws/settings.go
  storage/postgres/notificator.go
  storage/postgres/notificator_test.go
  test/ws_notification_test/ws_notification_test.go
Labels: request review

#337 Introduce Access Level
  api/filters/basic_authentication.go
  api/filters/tenant_filter.go
  api/filters/tenant_filter_test.go
  api/healthcheck/healthcheck_controller_test.go
  pkg/multitenancy/token_extraction.go
  pkg/multitenancy/token_extraction_test.go
  pkg/security/authenticators/oidc_authenticator.go
  pkg/security/filters/middlewares/authrization.go
  pkg/security/filters/middlewares/middlewares_test.go
  pkg/security/http/auth.go
  pkg/security/http/httpfakes/fake_authorizer.go
  pkg/web/user.go
  test/list.go
  test/test.go
Labels: request review

#336 Trim down interceptable repository code
  Gopkg.lock
  api/base_controller.go
  storage/interceptable_repository.go
  storage/interceptors_create.go
  storage/postgres/storage.go
Labels: request review

#287 [Fixit] Change parser to ANTLR4
  Gopkg.lock
  Gopkg.toml
  Makefile
  api/filters/selection_criteria.go
  cmd/smgen/api_type_template.go
  docs/usage/labels.md
  pkg/log/formatter.go
  pkg/query/Query.g4
  pkg/query/listener.go
  pkg/query/operators.go
  pkg/query/parser/Query.interp
  pkg/query/parser/Query.tokens
  pkg/query/parser/QueryLexer.interp
  pkg/query/parser/QueryLexer.tokens
  pkg/query/parser/query_base_listener.go
  pkg/query/parser/query_lexer.go
  pkg/query/parser/query_listener.go
  pkg/query/parser/query_parser.go
  pkg/query/selection.go
  pkg/query/selection_test.go
  pkg/query/update.go
  pkg/query/update_test.go
  pkg/types/labels.go
  pkg/types/notification_gen.go
  pkg/types/platform_gen.go
  pkg/types/servicebroker_gen.go
  pkg/types/serviceoffering_gen.go
  pkg/types/serviceplan_gen.go
  pkg/types/visibility_gen.go
  pkg/util/api.go
  storage/interceptable_repository.go
  storage/notification_cleaner.go
  storage/postgres/keystore_test.go
  storage/postgres/labels.go
  storage/postgres/migrations/20190920103600_convert_timestamp_tz.up.sql
  storage/postgres/migrations/20190920103600_covert_timestamp_tz.down.sql
  test/broker_test/broker_test.go
  test/common/common.go
  test/common/test_context.go
  test/delete_list.go
  test/list.go
  test/notification_test/notification_test.go
  test/public_plans_interceptor_test/public_plans_test.go
  test/query_test/query_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/visibility_test/visibility_test.go
Labels: breaking change, enhancement, request review
