Repository Peripli/service-manager, pull requests merged in 2019-01, with the labels that each got.

#196 Visibility Labels
  api/api.go
  api/broker/broker_controller.go
  api/filters/free_plans.go
  api/filters/selection_criteria.go
  api/osb/broker_fetcher.go
  api/platform/platform_controller.go
  api/service_offering/service_offering_controller.go
  api/service_plan/service_plan_controller.go
  api/visibility/visibility.go
  api/visibility/visibility_controller.go
  pkg/env/envfakes/fake_environment.go
  pkg/health/healthfakes/fake_aggregation_policy.go
  pkg/health/healthfakes/fake_indicator.go
  pkg/query/query_suite_test.go
  pkg/query/selection.go
  pkg/query/selection_test.go
  pkg/query/update.go
  pkg/query/update_test.go
  pkg/security/securityfakes/fake_authenticator.go
  pkg/security/securityfakes/fake_authorizer.go
  pkg/security/securityfakes/fake_encrypter.go
  pkg/security/securityfakes/fake_key_fetcher.go
  pkg/security/securityfakes/fake_key_setter.go
  pkg/security/securityfakes/fake_token_data.go
  pkg/security/securityfakes/fake_token_verifier.go
  pkg/types/labels.go
  pkg/types/visibility.go
  pkg/util/errors.go
  pkg/util/errors_test.go
  pkg/web/webfakes/fake_filter.go
  pkg/web/webfakes/fake_handler.go
  storage/interfaces.go
  storage/postgres/abstract.go
  storage/postgres/abstract_test.go
  storage/postgres/labels.go
  storage/postgres/labels_test.go
  storage/postgres/migrations/005_visibility_labels.down.sql
  storage/postgres/migrations/005_visibility_labels.up.sql
  storage/postgres/postgresfakes/fake_pg_db.go
  storage/postgres/types.go
  storage/postgres/visibility.go
  storage/storagefakes/fake_credentials.go
  storage/storagefakes/fake_service_offering.go
  storage/storagefakes/fake_storage.go
  test/visibility_test/visibility_test.go
Labels: To be merged, request review

#210 Allow multiple labels querying
  pkg/query/selection_test.go
  storage/postgres/abstract_test.go
  storage/postgres/labels.go
  storage/postgres/labels_test.go
  test/visibility_test/visibility_test.go
Labels: bug

#214 Enable fieldQuerying on all APIs, parameterize API tests
  Gopkg.lock
  api/api.go
  api/broker/broker.go
  api/broker/broker_controller.go
  api/filters/authn/basic/filter.go
  api/platform/platform.go
  api/platform/platform_controller.go
  api/service_offering/service_offering_controller.go
  api/service_plan/service_plan_controller.go
  application.yml
  pkg/log/context.go
  pkg/query/selection.go
  pkg/query/selection_test.go
  pkg/sm/sm.go
  pkg/types/service_plan.go
  pkg/util/slice/strings.go
  storage/interfaces.go
  storage/postgres/abstract.go
  storage/postgres/abstract_test.go
  storage/postgres/broker.go
  storage/postgres/labels.go
  storage/postgres/labels_test.go
  storage/postgres/platform.go
  storage/postgres/security.go
  storage/postgres/service_offering.go
  storage/postgres/service_plan.go
  test/broker_test/broker_test.go
  test/common/broker.go
  test/common/catalog.go
  test/common/common.go
  test/common/test_context.go
  test/delete.go
  test/delete_list.go
  test/filter_test/filter_test.go
  test/filter_test/free_plans_test.go
  test/get.go
  test/list.go
  test/osb_test/osb_test.go
  test/platform_test/platform_test.go
  test/plugin_test/plugin_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/test.go
  test/visibility_test/visibility_test.go
Labels: breaking change, request review

#215 Add Labels To Service Brokers
  api/broker/broker_controller.go
  pkg/security/filters/required_authz.go
  pkg/security/filters/required_test.go
  pkg/types/broker.go
  pkg/web/webfakes/fake_data.go
  storage/interfaces.go
  storage/postgres/abstract.go
  storage/postgres/broker.go
  storage/postgres/migrations/006_broker_labels.down.sql
  storage/postgres/migrations/006_broker_labels.up.sql
  storage/postgres/types.go
  storage/postgres/visibility.go
  storage/storagefakes/fake_service_offering.go
  test/broker_test/broker_test.go
  test/common/test_context.go
  test/visibility_test/visibility_test.go
Labels: request review

#208 Labels and querying doc
  docs/usage/labels.md
Labels: request review

#220 make public plans filter configurable
  api/api.go
  api/filters/public_plans.go
  test/filter_test/public_plans_test.go
Labels: request review

#222 handle error from client response
  pkg/util/api_test.go
  pkg/util/errors.go
  pkg/util/errors_test.go
Labels: request review

#221 Adjust label errors
  api/broker/broker_controller.go
  api/visibility/visibility_controller.go
  pkg/query/selection.go
  pkg/query/update.go
  pkg/query/update_test.go
  pkg/util/errors.go
  storage/postgres/abstract.go
  storage/postgres/labels.go
  test/broker_test/broker_test.go
  test/visibility_test/visibility_test.go
Labels: request review
