Repository Peripli/service-manager, pull requests merged in 2020-03, with the labels that each got.

#438 Generalize instance visibility checks
  Gopkg.lock
  api/api.go
  api/filters/check_instance_visibility_filter.go
  api/filters/service_binding_strip_filter.go
  api/filters/service_instance_strip_filter.go
  pkg/sm/sm.go
  storage/interceptors/smaap_service_binding_interceptor.go
  storage/interceptors/smaap_service_instance_interceptor.go
  test/service_instance_test/service_instance_test.go
  test/test.go
Labels: 👋request review

#449 Credentials integrity startup
  pkg/sm/sm.go
  storage/integrity_repository.go
  storage/postgres/labels.go
Labels: bug, priority/critical, 👋request review

#443 Credentials API
  Gopkg.lock
  api/api.go
  api/credentials_controller.go
  api/extensions/security/authn.go
  api/osb/check_instance_visibility_plugin.go
  api/osb/store_instances_plugin.go
  pkg/security/authenticators/basic_authentication.go
  pkg/security/authenticators/basic_authentication_test.go
  pkg/types/broker_platform_credential.go
  pkg/types/brokerplatformcredential_gen.go
  pkg/util/credentials.go
  pkg/web/routes.go
  storage/interceptors/broker_notifications_interceptor.go
  storage/interceptors/notifications_interceptor.go
  storage/interceptors/visibility_notifications_interceptor.go
  storage/postgres/broker_platform_credential.go
  storage/postgres/brokerplatformcredential_gen.go
  storage/postgres/keystore_test.go
  storage/postgres/locker_test.go
  storage/postgres/migrations/20200221152000_broker_platform_credentials.down.sql
  storage/postgres/migrations/20200221152000_broker_platform_credentials.up.sql
  storage/postgres/storage.go
  test/auth_test/auth_test.go
  test/common/test_context.go
  test/filter_test/filter_test.go
  test/operations_test/operations_test.go
  test/osb_test/bind_test.go
  test/osb_test/catalog_test.go
  test/osb_test/deprovision_test.go
  test/osb_test/osb_suite_test.go
  test/osb_test/poll_binding_last_operation_test.go
  test/osb_test/poll_instance_last_operation_test.go
  test/osb_test/post_binding_adapt_credentials_test.go
  test/osb_test/provision_test.go
  test/osb_test/unbind_test.go
  test/osb_test/update_instance_test.go
  test/plugin_test/plugin_test.go
  test/security_test/security_test.go
  test/test.go
Labels: 👋request review

#456 Fix Rescheduling of Instance/Binding operations
  Gopkg.lock
  operations/maintainer.go
  storage/interceptors/unique_binding_names_iterceptor.go
  storage/interceptors/unique_instance_names_iterceptor.go
  test/service_binding_test/service_binding_test.go
  test/service_instance_test/service_instance_test.go
  test/test.go
Labels: 👋request review

#457 Multi authenticator
  test/common/oauth_server.go
  test/common/test_context.go
Labels: 👋request review

#460 Broker platform credentials integrity
  pkg/sm/sm.go
  pkg/types/broker_platform_credential.go
  storage/postgres/broker_platform_credential.go
  storage/postgres/keystore_test.go
  storage/postgres/locker_test.go
  storage/postgres/migrations/20200309095000_credentials_integrity.down.sql
  storage/postgres/migrations/20200309095000_credentials_integrity.up.sql
  storage/postgres/migrations/20200309165500_broker_platform_credentials_integrity.down.sql
  storage/postgres/migrations/20200309165500_broker_platform_credentials_integrity.up.sql
Labels: 👋request review

#453 Credentials integrity
  pkg/security/encrypter_test.go
  pkg/security/integrity.go
  pkg/security/integrity_test.go
  pkg/security/security_suite_test.go
  pkg/security/securityfakes/fake_integrity_processor.go
  pkg/sm/sm.go
  pkg/types/broker_platform_credential.go
  pkg/types/credentials.go
  pkg/types/platform.go
  pkg/types/service_binding.go
  pkg/types/service_broker.go
  storage/integrity_repository.go
  storage/integrity_repository_test.go
  storage/interfaces.go
  storage/postgres/broker.go
  storage/postgres/broker_platform_credential.go
  storage/postgres/keystore_test.go
  storage/postgres/labels.go
  storage/postgres/locker_test.go
  storage/postgres/migrations/20200309095000_credentials_integrity.down.sql
  storage/postgres/migrations/20200309095000_credentials_integrity.up.sql
  storage/postgres/migrations/20200309165500_broker_platform_credentials_integrity.down.sql
  storage/postgres/migrations/20200309165500_broker_platform_credentials_integrity.up.sql
  storage/postgres/platform.go
  storage/postgres/service_binding.go
  storage/postgres/storage_test.go
Labels: 👋request review

#448 Transitive resources
  api/base_controller.go
  operations/opcontext/context.go
  operations/scheduler.go
  pkg/types/base.go
  pkg/types/interfaces.go
  pkg/types/operation.go
  pkg/types/service_binding.go
  pkg/types/service_broker.go
  pkg/types/service_instance.go
  pkg/web/api.go
  storage/interceptable_repository.go
  storage/interceptors/broker_create_catalog_interceptor.go
  storage/interceptors/broker_public_plans_interceptor.go
  storage/interceptors/smaap_service_binding_interceptor.go
  storage/interceptors/smaap_service_instance_interceptor.go
  storage/postgres/keystore_test.go
  storage/postgres/locker_test.go
  storage/postgres/migrations/20200226131000_operations_resources.down.sql
  storage/postgres/migrations/20200226131000_operations_resources.up.sql
  storage/postgres/operation.go
  storage/postgres/scheme_test.go
  test/broker_test/broker_test.go
  test/common/operation.go
  test/delete_list.go
  test/get.go
  test/notification_test/notification_test.go
  test/platform_test/platform_test.go
  test/service_binding_test/service_binding_test.go
  test/service_instance_test/service_instance_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/visibility_test/visibility_test.go
Labels: 👋request review

#463 Fix attach last operation
  api/base_controller.go
Labels: 👋request review

#461 Delete CODEOWNERS
  CODEOWNERS
Labels: 👋request review

#446 Notifications ready
  api/base_controller.go
  operations/opcontext/context.go
  operations/scheduler.go
  pkg/sm/sm.go
  pkg/types/base.go
  pkg/types/interfaces.go
  pkg/types/operation.go
  pkg/types/service_binding.go
  pkg/types/service_broker.go
  pkg/types/service_instance.go
  pkg/web/api.go
  storage/interceptable_repository.go
  storage/interceptors/broker_create_catalog_interceptor.go
  storage/interceptors/broker_notifications_interceptor.go
  storage/interceptors/broker_public_plans_interceptor.go
  storage/interceptors/notifications_interceptor.go
  storage/interceptors/smaap_service_binding_interceptor.go
  storage/interceptors/smaap_service_instance_interceptor.go
  storage/interceptors/unique_binding_names_iterceptor.go
  storage/interceptors/unique_instance_names_iterceptor.go
  storage/postgres/keystore_test.go
  storage/postgres/locker_test.go
  storage/postgres/migrations/20200311131000_operations_resources.down.sql
  storage/postgres/migrations/20200311131000_operations_resources.up.sql
  storage/postgres/operation.go
  storage/postgres/scheme_test.go
  test/broker_test/broker_test.go
  test/common/operation.go
  test/delete_list.go
  test/get.go
  test/notification_test/notification_test.go
  test/platform_test/platform_test.go
  test/public_plans_interceptor_test/public_plans_test.go
  test/service_binding_test/service_binding_test.go
  test/service_instance_test/service_instance_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/test.go
  test/visibility_test/visibility_test.go
Labels: topic, 👋request review

#466 Allow Broker Catalog ID updates
  storage/interceptors/broker_update_catalog_interceptor.go
  test/broker_test/broker_test.go
Labels: 👋request review

#454 Operations API
  api/api.go
  api/base_controller.go
  api/extensions/security/authn.go
  api/filters/oidc_authentication.go
  api/operations_controller.go
  api/service_binding_controller.go
  api/service_instance_controller.go
  pkg/query/listener.go
  pkg/web/routes.go
  test/auth_test/auth_test.go
  test/common/common.go
  test/delete.go
  test/delete_list.go
  test/get.go
  test/list.go
  test/operations_test/operations_test.go
  test/service_binding_test/service_binding_test.go
  test/service_instance_test/service_instance_test.go
  test/test.go
Labels: 👋request review

#470 SMaaP to do async unbind only when binding is retrievable
  storage/interceptors/smaap_service_binding_interceptor.go
  test/common/catalog.go
  test/service_binding_test/service_binding_test.go
Labels: 👋request review

#469 Fix ShareLock deadlock
  storage/encrypting_repository.go
  storage/integrity_repository.go
  storage/interceptable_repository.go
  storage/interceptable_repository_test.go
  storage/interfaces.go
  storage/postgres/query_builder.go
  storage/postgres/storage.go
  storage/storagefakes/fake_storage.go
Labels: 👋request review

#473 Configure default http client timeout
  api/osb/catalog_fetcher.go
  application.yml
  pkg/httpclient/settings.go
  storage/interceptable_repository.go
  test/broker_test/broker_test.go
  test/common/application.yml
  test/common/test_context.go
  test/configuration_test/configuration_test.go
  test/osb_test/osb_suite_test.go
Labels: 👋request review

#465 Adding support for broker tls based authentication
  api/osb/catalog_fetcher.go
  api/osb/catalog_fetcher_test.go
  api/osb/osb_controller.go
  api/osb/osb_controller_test.go
  pkg/client/broker_client.go
  pkg/client/broker_transport.go
  pkg/httpclient/settings.go
  pkg/sm/sm.go
  pkg/types/credentials.go
  pkg/types/service_broker.go
  pkg/util/api.go
  pkg/util/client.go
  pkg/util/client_test.go
  storage/interceptors/smaap_service_instance_interceptor.go
  storage/postgres/broker.go
  storage/postgres/migrations/20200219214200_broker_tls.down.sql
  storage/postgres/migrations/20200219214200_broker_tls.up.sql
  test/broker_test/broker_test.go
  test/common/application.yml
  test/common/broker.go
  test/common/common.go
  test/common/service_instance.go
  test/common/test_context.go
  test/configuration_test/configuration_test.go
  test/filter_test/filter_test.go
  test/interceptors_test/interceptors_test.go
  test/notification_test/notification_test.go
  test/operations_test/operations_test.go
  test/osb_test/catalog_test.go
  test/osb_test/osb_suite_test.go
  test/osb_test/provision_test.go
  test/plugin_test/plugin_test.go
  test/public_plans_interceptor_test/public_plans_test.go
  test/service_binding_test/service_binding_test.go
  test/service_instance_test/service_instance_test.go
  test/service_offering_test/service_offering_test.go
  test/service_plan_test/service_plan_test.go
  test/tls_settings/settings.go
  test/visibility_test/visibility_test.go
Labels: 👋request review

#476 Adjust http client test timeouts
  test/broker_test/broker_test.go
  test/common/application.yml
  test/configuration_test/configuration_test.go
Labels: 👋request review
